### ISSUE TITLE
具体功能?

### ISSUE THREAD

**Issue by itkang** [iotalabs/alexandrite#2]
能在README下面讲下这个库的具体功能吗?

**Comment by AlexanderChen1989** [comment]
我添加了README了，谢谢关注。

**Comment by AlexanderChen1989** [comment]
欢迎在issues里面提问题和想法。

**Comment by itkang** [comment]
https://github.com/QianmiOpen/bugatti

功能是不是跟这个相似

-- 
Itkang@126.com

开 2016年5月30日 在 20:31:38, Alexander (notifications@github.com) 写到:

欢迎在issues里面提问题和想法。
